// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SecondaryValue struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *_struct.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SecondaryValue) Reset()         { *m = SecondaryValue{} }
func (m *SecondaryValue) String() string { return proto.CompactTextString(m) }
func (*SecondaryValue) ProtoMessage()    {}
func (*SecondaryValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *SecondaryValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecondaryValue.Unmarshal(m, b)
}
func (m *SecondaryValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecondaryValue.Marshal(b, m, deterministic)
}
func (m *SecondaryValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecondaryValue.Merge(m, src)
}
func (m *SecondaryValue) XXX_Size() int {
	return xxx_messageInfo_SecondaryValue.Size(m)
}
func (m *SecondaryValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SecondaryValue.DiscardUnknown(m)
}

var xxx_messageInfo_SecondaryValue proto.InternalMessageInfo

func (m *SecondaryValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecondaryValue) GetValue() *_struct.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type UpsertAttributes struct {
	// Item value
	Value *_struct.Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// All of the secondary accessable key:value pairs
	SecondaryKeys        []*SecondaryValue `protobuf:"bytes,2,rep,name=secondaryKeys,proto3" json:"secondaryKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpsertAttributes) Reset()         { *m = UpsertAttributes{} }
func (m *UpsertAttributes) String() string { return proto.CompactTextString(m) }
func (*UpsertAttributes) ProtoMessage()    {}
func (*UpsertAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *UpsertAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertAttributes.Unmarshal(m, b)
}
func (m *UpsertAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertAttributes.Marshal(b, m, deterministic)
}
func (m *UpsertAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertAttributes.Merge(m, src)
}
func (m *UpsertAttributes) XXX_Size() int {
	return xxx_messageInfo_UpsertAttributes.Size(m)
}
func (m *UpsertAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertAttributes proto.InternalMessageInfo

func (m *UpsertAttributes) GetValue() *_struct.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UpsertAttributes) GetSecondaryKeys() []*SecondaryValue {
	if m != nil {
		return m.SecondaryKeys
	}
	return nil
}

type DeleteAttributes struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAttributes) Reset()         { *m = DeleteAttributes{} }
func (m *DeleteAttributes) String() string { return proto.CompactTextString(m) }
func (*DeleteAttributes) ProtoMessage()    {}
func (*DeleteAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *DeleteAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAttributes.Unmarshal(m, b)
}
func (m *DeleteAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAttributes.Marshal(b, m, deterministic)
}
func (m *DeleteAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAttributes.Merge(m, src)
}
func (m *DeleteAttributes) XXX_Size() int {
	return xxx_messageInfo_DeleteAttributes.Size(m)
}
func (m *DeleteAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAttributes proto.InternalMessageInfo

func (m *DeleteAttributes) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type Item struct {
	// ID and timestamp are required regardless of operation
	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// You can only perform one or the other operations
	//
	// Types that are valid to be assigned to Attributes:
	//	*Item_Upsert
	//	*Item_Delete
	Attributes           isItem_Attributes `protobuf_oneof:"attributes"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isItem_Attributes interface {
	isItem_Attributes()
}

type Item_Upsert struct {
	Upsert *UpsertAttributes `protobuf:"bytes,3,opt,name=upsert,proto3,oneof"`
}

type Item_Delete struct {
	Delete *DeleteAttributes `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*Item_Upsert) isItem_Attributes() {}

func (*Item_Delete) isItem_Attributes() {}

func (m *Item) GetAttributes() isItem_Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Item) GetUpsert() *UpsertAttributes {
	if x, ok := m.GetAttributes().(*Item_Upsert); ok {
		return x.Upsert
	}
	return nil
}

func (m *Item) GetDelete() *DeleteAttributes {
	if x, ok := m.GetAttributes().(*Item_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Item) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Item_Upsert)(nil),
		(*Item_Delete)(nil),
	}
}

func init() {
	proto.RegisterType((*SecondaryValue)(nil), "storage.SecondaryValue")
	proto.RegisterType((*UpsertAttributes)(nil), "storage.UpsertAttributes")
	proto.RegisterType((*DeleteAttributes)(nil), "storage.DeleteAttributes")
	proto.RegisterType((*Item)(nil), "storage.Item")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x6e, 0xf2, 0x30,
	0x14, 0xc5, 0xbf, 0x04, 0x3e, 0xfe, 0x5c, 0x5a, 0x84, 0x3c, 0xb4, 0x6e, 0xc5, 0x80, 0x32, 0x31,
	0x20, 0x23, 0xc1, 0xdc, 0xa1, 0x88, 0xa1, 0xa8, 0x9b, 0xab, 0x76, 0xe8, 0xe6, 0x90, 0xdb, 0x28,
	0x52, 0x82, 0x23, 0xfb, 0xa6, 0x12, 0x53, 0x5f, 0xa8, 0x0f, 0x59, 0xc5, 0x49, 0xa0, 0x64, 0xea,
	0x76, 0x73, 0x72, 0xce, 0xc9, 0xf9, 0x05, 0x20, 0x21, 0xcc, 0x44, 0x6e, 0x34, 0x69, 0xd6, 0xb7,
	0xa4, 0x8d, 0x8a, 0xf1, 0x7e, 0x1a, 0x6b, 0x1d, 0xa7, 0xb8, 0x74, 0x72, 0x58, 0x7c, 0x2c, 0x2d,
	0x99, 0x62, 0x4f, 0x95, 0x2d, 0x90, 0x30, 0x7e, 0xc1, 0xbd, 0x3e, 0x44, 0xca, 0x1c, 0xdf, 0x54,
	0x5a, 0x20, 0x63, 0xd0, 0x3d, 0xa8, 0x0c, 0xb9, 0x37, 0xf3, 0xe6, 0x43, 0xe9, 0x6e, 0xb6, 0x80,
	0xff, 0x9f, 0xe5, 0x4b, 0xee, 0xcf, 0xbc, 0xf9, 0x68, 0x75, 0x23, 0xaa, 0x4e, 0xd1, 0x74, 0x0a,
	0x17, 0x95, 0x95, 0x29, 0xf8, 0x82, 0xc9, 0x6b, 0x6e, 0xd1, 0xd0, 0x23, 0x91, 0x49, 0xc2, 0x82,
	0xd0, 0x9e, 0x1b, 0xbc, 0x3f, 0x34, 0xb0, 0x07, 0xb8, 0xb6, 0xcd, 0xaa, 0x67, 0x3c, 0x5a, 0xee,
	0xcf, 0x3a, 0xf3, 0xd1, 0xea, 0x56, 0xd4, 0x50, 0xe2, 0x72, 0xb3, 0xbc, 0x74, 0x07, 0x0b, 0x98,
	0x6c, 0x31, 0x45, 0xc2, 0x5f, 0x03, 0x38, 0xf4, 0x23, 0xa7, 0x45, 0x6e, 0xc2, 0x40, 0x36, 0x8f,
	0xc1, 0xb7, 0x07, 0xdd, 0x1d, 0x61, 0xc6, 0xc6, 0xe0, 0xef, 0xb6, 0x35, 0xb7, 0xbf, 0xdb, 0xb2,
	0x29, 0x0c, 0x29, 0xc9, 0xd0, 0x92, 0xca, 0x72, 0x47, 0xde, 0x91, 0x67, 0x81, 0xad, 0xa1, 0x57,
	0x38, 0x4a, 0xde, 0x71, 0x48, 0x77, 0xa7, 0x71, 0x6d, 0xf8, 0xa7, 0x7f, 0xb2, 0xb6, 0x96, 0xa1,
	0xea, 0xb3, 0xbc, 0xdb, 0x0a, 0xb5, 0x07, 0x97, 0xa1, 0xca, 0xba, 0xb9, 0x02, 0x50, 0x27, 0x7d,
	0x03, 0xef, 0x83, 0xe6, 0xa7, 0x85, 0x3d, 0x77, 0xad, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4,
	0x18, 0x83, 0x3c, 0xf9, 0x01, 0x00, 0x00,
}
