// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumOperationType int32

const (
	EnumOperationType_GET    EnumOperationType = 0
	EnumOperationType_SET    EnumOperationType = 1
	EnumOperationType_DELETE EnumOperationType = 2
)

var EnumOperationType_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "DELETE",
}

var EnumOperationType_value = map[string]int32{
	"GET":    0,
	"SET":    1,
	"DELETE": 2,
}

func (x EnumOperationType) String() string {
	return proto.EnumName(EnumOperationType_name, int32(x))
}

func (EnumOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{0}
}

type EnumStatusCode int32

const (
	EnumStatusCode_UNKNOWN         EnumStatusCode = 0
	EnumStatusCode_SUCCESS         EnumStatusCode = 1
	EnumStatusCode_NOT_FOUND       EnumStatusCode = 2
	EnumStatusCode_ALREADY_DELETED EnumStatusCode = 3
)

var EnumStatusCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "NOT_FOUND",
	3: "ALREADY_DELETED",
}

var EnumStatusCode_value = map[string]int32{
	"UNKNOWN":         0,
	"SUCCESS":         1,
	"NOT_FOUND":       2,
	"ALREADY_DELETED": 3,
}

func (x EnumStatusCode) String() string {
	return proto.EnumName(EnumStatusCode_name, int32(x))
}

func (EnumStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{1}
}

// Default value means all of these are off, meaning a default request will return you:
// Only the key and there will be no limit
type Config struct {
	// KeysOnly makes sense only in the context of a non-direct query
	Data bool `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	// Don't try to control the iterator through the RPC, let the interface take care of that and sent to a different
	// handler if this is set
	// bool singlePayload = 2;
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Type                 EnumOperationType `protobuf:"varint,3,opt,name=type,proto3,enum=storage.EnumOperationType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

func (m *Config) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Config) GetType() EnumOperationType {
	if m != nil {
		return m.Type
	}
	return EnumOperationType_GET
}

// Filterset contains the set of information making up the filter operation
type FilterSet struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op                   string   `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterSet) Reset()         { *m = FilterSet{} }
func (m *FilterSet) String() string { return proto.CompactTextString(m) }
func (*FilterSet) ProtoMessage()    {}
func (*FilterSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{1}
}

func (m *FilterSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterSet.Unmarshal(m, b)
}
func (m *FilterSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterSet.Marshal(b, m, deterministic)
}
func (m *FilterSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterSet.Merge(m, src)
}
func (m *FilterSet) XXX_Size() int {
	return xxx_messageInfo_FilterSet.Size(m)
}
func (m *FilterSet) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterSet.DiscardUnknown(m)
}

var xxx_messageInfo_FilterSet proto.InternalMessageInfo

func (m *FilterSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FilterSet) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *FilterSet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Filter struct {
	// The ID will be - key:op:value; this might be used in the return
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// These values will be AND'd together during the query
	Set []*FilterSet `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`
	// Filter-level config; the global override config will be taken into account BEFORE the local config
	Cfg                  *Config  `protobuf:"bytes,3,opt,name=cfg,proto3" json:"cfg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Filter) GetSet() []*FilterSet {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *Filter) GetCfg() *Config {
	if m != nil {
		return m.Cfg
	}
	return nil
}

type Direct struct {
	Type                 EnumOperationType `protobuf:"varint,1,opt,name=type,proto3,enum=storage.EnumOperationType" json:"type,omitempty"`
	Items                []*Item           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Direct) Reset()         { *m = Direct{} }
func (m *Direct) String() string { return proto.CompactTextString(m) }
func (*Direct) ProtoMessage()    {}
func (*Direct) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{3}
}

func (m *Direct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direct.Unmarshal(m, b)
}
func (m *Direct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direct.Marshal(b, m, deterministic)
}
func (m *Direct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direct.Merge(m, src)
}
func (m *Direct) XXX_Size() int {
	return xxx_messageInfo_Direct.Size(m)
}
func (m *Direct) XXX_DiscardUnknown() {
	xxx_messageInfo_Direct.DiscardUnknown(m)
}

var xxx_messageInfo_Direct proto.InternalMessageInfo

func (m *Direct) GetType() EnumOperationType {
	if m != nil {
		return m.Type
	}
	return EnumOperationType_GET
}

func (m *Direct) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Override struct {
	// Limit override for the entire query
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Override) Reset()         { *m = Override{} }
func (m *Override) String() string { return proto.CompactTextString(m) }
func (*Override) ProtoMessage()    {}
func (*Override) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{4}
}

func (m *Override) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Override.Unmarshal(m, b)
}
func (m *Override) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Override.Marshal(b, m, deterministic)
}
func (m *Override) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Override.Merge(m, src)
}
func (m *Override) XXX_Size() int {
	return xxx_messageInfo_Override.Size(m)
}
func (m *Override) XXX_DiscardUnknown() {
	xxx_messageInfo_Override.DiscardUnknown(m)
}

var xxx_messageInfo_Override proto.InternalMessageInfo

func (m *Override) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Status struct {
	Code                 EnumStatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=storage.EnumStatusCode" json:"code,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{5}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() EnumStatusCode {
	if m != nil {
		return m.Code
	}
	return EnumStatusCode_UNKNOWN
}

func (m *Status) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("storage.EnumOperationType", EnumOperationType_name, EnumOperationType_value)
	proto.RegisterEnum("storage.EnumStatusCode", EnumStatusCode_name, EnumStatusCode_value)
	proto.RegisterType((*Config)(nil), "storage.Config")
	proto.RegisterType((*FilterSet)(nil), "storage.FilterSet")
	proto.RegisterType((*Filter)(nil), "storage.Filter")
	proto.RegisterType((*Direct)(nil), "storage.Direct")
	proto.RegisterType((*Override)(nil), "storage.Override")
	proto.RegisterType((*Status)(nil), "storage.Status")
}

func init() { proto.RegisterFile("operation.proto", fileDescriptor_619dee0fded31cb3) }

var fileDescriptor_619dee0fded31cb3 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x61, 0x8b, 0xda, 0x40,
	0x14, 0xbc, 0x24, 0x1a, 0xf5, 0xd9, 0xd3, 0xf4, 0xb5, 0x50, 0xb9, 0x4f, 0x69, 0xda, 0x0f, 0x72,
	0x05, 0xa1, 0xf6, 0x17, 0x5c, 0x93, 0xbd, 0x22, 0x3d, 0x12, 0xd8, 0x44, 0x8e, 0x16, 0xca, 0x11,
	0xcd, 0x2a, 0x4b, 0xd5, 0x0d, 0x9b, 0xf5, 0xc0, 0x7f, 0x5f, 0x76, 0x37, 0xe7, 0xf5, 0xe8, 0x97,
	0x7e, 0x9b, 0xb7, 0x6f, 0x32, 0x33, 0x6f, 0x08, 0x8c, 0x45, 0xcd, 0x64, 0xa9, 0xb8, 0x38, 0xcc,
	0x6a, 0x29, 0x94, 0xc0, 0x5e, 0xa3, 0x84, 0x2c, 0xb7, 0xec, 0x0a, 0xb8, 0x62, 0x7b, 0xfb, 0x18,
	0xad, 0xc0, 0x8f, 0xc5, 0x61, 0xc3, 0xb7, 0x88, 0xd0, 0xa9, 0x4a, 0x55, 0x4e, 0x9c, 0xd0, 0x99,
	0xf6, 0xa9, 0xc1, 0xf8, 0x16, 0xba, 0x3b, 0xbe, 0xe7, 0x6a, 0xe2, 0x86, 0xce, 0xd4, 0xa3, 0x76,
	0xc0, 0x19, 0x74, 0xd4, 0xa9, 0x66, 0x13, 0x2f, 0x74, 0xa6, 0xa3, 0xf9, 0xd5, 0xac, 0xd5, 0x9d,
	0x91, 0xc3, 0x71, 0x9f, 0x3d, 0x99, 0x16, 0xa7, 0x9a, 0x51, 0xc3, 0x8b, 0x62, 0x18, 0xdc, 0xf2,
	0x9d, 0x62, 0x32, 0x67, 0x0a, 0x03, 0xf0, 0x7e, 0xb3, 0x93, 0x71, 0x19, 0x50, 0x0d, 0x71, 0x04,
	0xae, 0xa8, 0x8d, 0xc3, 0x80, 0xba, 0xa2, 0xd6, 0xa6, 0x8f, 0xe5, 0xee, 0x68, 0xf5, 0x5f, 0x51,
	0x3b, 0x44, 0x25, 0xf8, 0x56, 0x44, 0xf3, 0x17, 0x49, 0x2b, 0xe0, 0x2e, 0x12, 0xfc, 0x08, 0x5e,
	0xc3, 0x74, 0x44, 0x6f, 0x3a, 0x9c, 0xe3, 0x39, 0xcd, 0xd9, 0x92, 0xea, 0x35, 0xbe, 0x07, 0x6f,
	0xbd, 0xd9, 0x1a, 0xcd, 0xe1, 0x7c, 0x7c, 0x66, 0xd9, 0xe3, 0xa9, 0xde, 0x45, 0xbf, 0xc0, 0x4f,
	0xb8, 0x64, 0xeb, 0xe7, 0x0b, 0x9d, 0xff, 0xbb, 0x10, 0x3f, 0x40, 0x57, 0x77, 0xda, 0xb4, 0x21,
	0x2e, 0xcf, 0x1f, 0x2c, 0x14, 0xdb, 0x53, 0xbb, 0x8b, 0x42, 0xe8, 0x67, 0x8f, 0x4c, 0x4a, 0x5e,
	0xb1, 0xe7, 0x62, 0xb5, 0x43, 0xb7, 0x2d, 0x36, 0xba, 0x07, 0x3f, 0x57, 0xa5, 0x3a, 0x36, 0xf8,
	0x09, 0x3a, 0x6b, 0x51, 0x3d, 0x05, 0x78, 0xf7, 0x22, 0x80, 0xa5, 0xc4, 0xa2, 0x62, 0xd4, 0x90,
	0x30, 0x84, 0x61, 0xc5, 0x9a, 0xb5, 0xe4, 0xb5, 0x8e, 0xd5, 0x36, 0xf9, 0xf7, 0xd3, 0xf5, 0x67,
	0x78, 0xfd, 0x4f, 0x74, 0xec, 0x81, 0xf7, 0x8d, 0x14, 0xc1, 0x85, 0x06, 0x39, 0x29, 0x02, 0x07,
	0x01, 0xfc, 0x84, 0xdc, 0x91, 0x82, 0x04, 0xee, 0x75, 0x0a, 0xa3, 0x97, 0x66, 0x38, 0x84, 0xde,
	0x32, 0xfd, 0x9e, 0x66, 0xf7, 0x69, 0x70, 0xa1, 0x87, 0x7c, 0x19, 0xc7, 0x24, 0xcf, 0x03, 0x07,
	0x2f, 0x61, 0x90, 0x66, 0xc5, 0xc3, 0x6d, 0xb6, 0x4c, 0x93, 0xc0, 0xc5, 0x37, 0x30, 0xbe, 0xb9,
	0xa3, 0xe4, 0x26, 0xf9, 0xf1, 0x60, 0xe5, 0x92, 0xc0, 0xfb, 0x0a, 0x3f, 0xfb, 0xe6, 0x8f, 0x5b,
	0x1d, 0x37, 0x2b, 0xdf, 0xa0, 0x2f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xb1, 0xbb, 0x54,
	0xa3, 0x02, 0x00, 0x00,
}
